-- MySQL Script generated by MySQL Workbench
-- Sat Sep 28 11:02:26 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema morningstar
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema morningstar
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `morningstar` ;
USE `morningstar` ;

-- -----------------------------------------------------
-- Table `morningstar`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `morningstar`.`produtos` (
  `idProduct` INT NOT NULL AUTO_INCREMENT,
  `productName` VARCHAR(100) NOT NULL UNIQUE,
  `productType` VARCHAR(50) NOT NULL,
  `manufactorer` VARCHAR(100) NOT NULL,
  `description` TEXT NULL,
  `dateTime` TIMESTAMP NOT NULL,
  PRIMARY KEY (`idProduct`),
  UNIQUE INDEX `name_UNIQUE` (`productName` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `morningstar`.`entradas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `morningstar`.`entradas` (
  `idEntrance` INT NOT NULL AUTO_INCREMENT,
  `idProduct` INT NULL,
  `quantity` INT(12) NOT NULL,
  `dateTime` TIMESTAMP NOT NULL,
  `produtos_idProduct` INT NOT NULL,
  PRIMARY KEY (`idEntrance`, `produtos_idProduct`),
  INDEX `fk_entradas_produtos_idx` (`produtos_idProduct` ASC) VISIBLE,
  CONSTRAINT `fk_entradas_produtos`
    FOREIGN KEY (`produtos_idProduct`)
    REFERENCES `morningstar`.`produtos` (`idProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `morningstar`.`saidas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `morningstar`.`saidas` (
  `idExit` INT NOT NULL AUTO_INCREMENT,
  `idProduct` INT NOT NULL,
  `quantity` INT(12) NOT NULL,
  `dateTime` TIMESTAMP NOT NULL,
  `produtos_idProduct` INT NOT NULL,
  PRIMARY KEY (`idExit`, `produtos_idProduct`),
  INDEX `fk_saidas_produtos1_idx` (`produtos_idProduct` ASC) VISIBLE,
  CONSTRAINT `fk_saidas_produtos1`
    FOREIGN KEY (`produtos_idProduct`)
    REFERENCES `morningstar`.`produtos` (`idProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
